# Generated by Django 5.0.8 on 2024-08-12 01:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("loans", "0002_alter_loan_taken_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Payment ID",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="External payment ID", max_length=60, unique=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Amout of the payment",
                        max_digits=20,
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Completed"), (2, "Rejected")],
                        help_text="Status of the payment",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loans.loan"
                    ),
                ),
            ],
        ),
    ]
