# Generated by Django 5.0.8 on 2024-08-11 22:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Loan ID",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="External if of the Loan", max_length=60, unique=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount with which the loan was created",
                        max_digits=12,
                    ),
                ),
                (
                    "outstanding",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount of customer loans",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Pending"),
                            (2, "Active"),
                            (3, "Rejected"),
                            (4, "Paid"),
                        ],
                        default=1,
                        help_text="Status of the loan",
                    ),
                ),
                (
                    "contract_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional field that can contain any value",
                        max_length=255,
                    ),
                ),
                ("maximum_payment_date", models.DateTimeField()),
                ("taken_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
